POST https://node-ygnp.onrender.com/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-ygnp.onrender.com/videos?search=node

###

PUT https://node-ygnp.onrender.com/videos/fa785fa5-75ed-4729-a7c5-9d13dc5bd270
Content-type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE https://node-ygnp.onrender.com/videos/fa785fa5-75ed-4729-a7c5-9d13dc5bd270
###